/// Flutter icons CCRIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CCRIcons
///      fonts:
///       - asset: fonts/CCRIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CCRIcons {
  CCRIcons._();

  static const _kFontFam = 'CCRIcons';
  static const _kFontPkg = null;

  static const IconData alerts = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alerts_black = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData avaliacoes = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cadastro = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_black = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coin = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delivery = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heartbeat = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData historico = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_black = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData intera__es = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_bag = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pin = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pin_black = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData placeholder = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData saude = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData speed = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData statistics = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_black = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData writing = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
